In [2]:
import fasttext

In [3]:
model=fasttext.load_model(r"E:\Natural Language Processing\Models\fastext_en\cc.en.300.bin")

In [4]:
model.get_nearest_neighbors("good")

[(0.7517593502998352, 'bad'),
 (0.7426098585128784, 'great'),
 (0.7299689054489136, 'decent'),
 (0.7123614549636841, 'nice'),
 (0.6796907186508179, 'Good'),
 (0.6737031936645508, 'excellent'),
 (0.669592022895813, 'goood'),
 (0.6602178812026978, 'ggod'),
 (0.6479219794273376, 'semi-good'),
 (0.6417751908302307, 'good.Good')]

In [14]:
model.get_analogies("programming","python","machine",k=5)

[(0.5779582262039185, 'machines'),
 (0.5246042013168335, 'programing'),
 (0.4868060052394867, 'machine-style'),
 (0.4831227660179138, 'machine.This'),
 (0.4776231348514557, 'pre-programming')]

In [7]:
import pandas as pd
import numpy as np

df=pd.read_csv("../Dataset/Twitter_Data.csv")
df.head()

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [9]:
from gensim.utils import simple_preprocess


df["clean_text"]=df["clean_text"].astype("str").apply(simple_preprocess)
df.head()

                                          clean_text  category
0  [when, modi, promised, minimum, government, ma...      -1.0
1  [talk, all, the, nonsense, and, continue, all,...       0.0
2  [what, did, just, say, vote, for, modi, welcom...       1.0
3  [asking, his, supporters, prefix, chowkidar, t...       1.0
4  [answer, who, among, these, the, most, powerfu...       1.0

In [17]:
def join_lines(list_value):
    text=" ".join(list_value)
    return text

df["clean_text"]=df["clean_text"].apply(join_lines)

In [19]:
Dataset="__label__"+df["category"].astype("str")+" "+df["clean_text"]

In [35]:
Dataset[:10]

0    __label__-1.0 when modi promised minimum gover...
1    __label__0.0 talk all the nonsense and continu...
2    __label__1.0 what did just say vote for modi w...
3    __label__1.0 asking his supporters prefix chow...
4    __label__1.0 answer who among these the most p...
5    __label__0.0 kiya tho refresh maarkefir commen...
6    __label__0.0 surat women perform yagna seeks d...
7    __label__0.0 this comes from cabinet which has...
8    __label__1.0 with upcoming election india saga...
9                __label__1.0 gandhi was gay does modi
dtype: object

In [21]:
from sklearn.model_selection import train_test_split

train,test=train_test_split(Dataset,random_state=42,test_size=.25)

In [23]:
display(train.shape)
display(test.shape)

(122235,)

(40745,)

## Fasttext requires text/csv format for train and test

In [27]:
train_file=train.to_csv("../Resource/train.text",index=False,header=False)
test_file=train.to_csv("../Resource/test.text",index=False,header=False)

In [28]:
trained_model=fasttext.train_supervised(input="../Resource/train.text",epoch=25, lr=1.0, wordNgrams=2)

In [29]:
test_result=trained_model.test("../Resource/test.text")

In [30]:
test_result

(122235, 0.9999427332597046, 0.9999427332597046)

In [31]:
trained_model.predict("modi speech today inspired me a lot about digital india initiative	")

(('__label__0.0',), array([0.99999571]))

In [32]:
trained_model.predict("modi has ruined small businesses through gst and demonetization	")

(('__label__-1.0',), array([1.00001001]))

In [ ]:
trained_model.predict("these leaders just talk, nothing actually happens")

(('__label__0.0',), array([1.00001001]))